### ISSUE TITLE
Is there a way to pass argument from view to OnSelect?

### ISSUE THREAD

**Issue by adithep** [sporto/elm-select#1]
Currently OnSelect will pass back model as argument back to update.

Is there a way to pass extra arguments from view to OnSelect?

**Comment by sporto** [comment]
Not now, can you give me an example?

**Comment by MarkNijhof** [comment]
I think you want a value to be passed along to the on select handler? You should look at partial application.

```
selectConfig : List String -> Select.Config Messages.Msg KeyValue
selectConfig names =
    Select.newConfig (ReportAutoSuggestOnSelect names) .value
        |> Select.withCutoff 12
```

and

```
(Html.map
    (ReportAutoSuggestSelectMsg names)
    (Select.view sc state data selectedValue)
)
```

```
   ReportAutoSuggestOnSelect (List String) (Maybe KeyValue)
   ReportAutoSuggestSelectMsg (List String) (Select.Msg KeyValue)
```

**Comment by sporto** [comment]
I think that partial application is sufficient here. Closing as this is not very clear.
