### ISSUE TITLE
Add arrow navigation

### ISSUE THREAD

**Issue by chazsconi** [sporto/elm-select#10]
Hi @sporto 

I would like to add this functionality (as per the TODO list), so that the user can navigate up and down the list with the arrow keys.

However, I think to achieve this will involve removing using the focus to highlight the item in the list that is currently selected (hence removing the `tabIndex 0` attribute) and instead store in the state which item is currently selected to in the list, and allow it to be highlighted with a style or class.

Do you think this is the correct approach?

Continuing to use focus, as far as I can see is problematic, as to change the focus explicitly involves using the `focus` function of `elm-lang/Dom` (so introducing another dependency) and getting the item that currently has focus is not possible through elm without using a port.

**Comment by sporto** [comment]
Hi @chazsconi 
Yes, I agree. I think we need to store the currently highlighted item in the state as you describe.
Thanks for looking into this.
