### ISSUE TITLE
Should disable HTML autocomplete for the Input element

### ISSUE THREAD

**Issue by chazsconi** [sporto/elm-select#13]
Either this should be disabled by default or the component should allow configuring of additional attributes using a `withInputAttributes` function.

Not only should `autocomplete="off"` be set but also `autocorrect="off"` as otherwise this causes keyboard suggestions in Mobile Safari (see screenshot)

I'm happy to fix this with a PR which either way is considered better.

![image](https://user-images.githubusercontent.com/2903865/29369290-7df06442-82a2-11e7-964b-c3c199f4da70.png)

**Comment by sporto** [comment]
Thanks, I think we make it disabled.
