### ISSUE TITLE
Should have more control over Clear button appearance

### ISSUE THREAD

**Issue by chazsconi** [sporto/elm-select#15]
Although class and style can be set, the icon cannot be changed and there are also several styles that are applied by default and thus cannot be overridden easily by a class.

Not sure the best way to do this - perhaps an alternative function can be passed in as a config option that will override the default `Clear.view`.

**Comment by sporto** [comment]
I think we add a config function `withCustomClearIcon` that renders your own html. Then we render that if present. Something like:

```
withCustomClearIcon : Maybe (Html Never) -> Config -> Config
```

**Comment by Munksgaard** [comment]
This would be great.

**Comment by Munksgaard** [comment]
As a temporary fix, if you just want to show another image, you can use the following snippet in your css:

```css
.elm-select-clear {
    content: url("close.svg");
}
```

**Comment by sporto** [comment]
version 4.1 includes `withClearHtml` for this
