### ISSUE TITLE
[Feature Request] Multiselect

### ISSUE THREAD

**Issue by jaredramirez** [sporto/elm-select#28]
First I would like to say that this package is really awesome!

I was wondering if a multiselect feature is on the roadmap at any point? Something along the lines of:
http://g.recordit.co/e76QjSyxJh.gif

(from https://jedwatson.github.io/react-select/)

I'm available to help work on this feature, but am wondering if you had already put any thought in to a feature like this?

**Comment by sporto** [comment]
Hi @jaredramirez thanks

This feature is not planned.
But there is a package that does something very similar. See https://github.com/larribas/elm-multi-input. Maybe this one does what you need?

**Comment by jaredramirez** [comment]
Thank for linking that! A combination of this package and that one is the feature I'm looking for. Rather than type in multiple inputs, i want to select the inputs from the menu.

If I were to implement this feature & PR, would it be accepted as part of this package? Or do you feel it's out of scope of this package's goal, and I should work on it separately?

**Comment by sporto** [comment]
I think this would be great. A PR will be welcome. But if we don't change the current look and behaviour when you only want one result. Meaning:

- There will be an option to specify if this is multi select

- When in single select mode it looks as it does now

![image](https://user-images.githubusercontent.com/1005498/40151681-c3bb89f8-59c4-11e8-9399-a00468e02b41.png)

- Then only in multi select we see those boxes around the items

![image](https://user-images.githubusercontent.com/1005498/40151706-e18822a2-59c4-11e8-9ba8-b6256f716b04.png)

**Comment by jaredramirez** [comment]
Cool! I'll keep this issue updated as I go with any question I may run into

**Comment by sporto** [comment]
This was done in https://github.com/sporto/elm-select/pull/30
