### ISSUE TITLE
Add an option to add styles/classes when the user has successfully selected an item

### ISSUE THREAD

**Issue by Munksgaard** [sporto/elm-select#38]
It would be nice to have something like `withSelectedClass` that allows us to put a specific style on input fields where the user has successfully selected something. I would use it to put a green border around required input fields where the user has successfully chosen an item.

**Comment by jaredramirez** [comment]
This would be great! As a workaround, you can use `withItemHtml` and pass in the currently selected value then if they are equal, apply your styling.

**Comment by sporto** [comment]
Version 4.2 includes `withItemSelectedAttrs` for this.
