### ISSUE TITLE
how can i inspect the dropdown?

### ISSUE THREAD

**Issue by danfitz36** [sporto/elm-select#44]
i want to be able to inspect and play around with styles, but I can't figure out how to keep the dropdown open long enough to learn anything about what's happening.

**Comment by jaredramirez** [comment]
Try giving the Elm debugger a shot. After you open the dropdown, open the debugger and go "backward in time" to when the dropdown was open. When you select a past message, the browser will freeze in that state and you can use the browser dev tools

**Comment by sporto** [comment]
This is a challenge with DOM that gets removed when clicking outside.
Another option in Chrome is to go to `sources` in the dev panel. Then open the dropdown and press F8. That should freeze the JS execution.
