### ISSUE TITLE
Don't search unless query is atleast 3 chars

### ISSUE THREAD

**Issue by MarkNijhof** [sporto/elm-select#8]
I would like to see `PrivateMsg` and `Select.Messages.Msg` exposed so I can have a bit more control over when a search happens.

``` 
           ReportAutoSuggestSelectMsg name subMsg ->
                let
                    _ =
                        Debug.log "M" subMsg
                in
                    case subMsg of
                        PrivateMsg subSubMsg ->
                            case subSubMsg of
                                OnQueryChange q ->
                                    if (length q) < 3 then
                                        ( model, Cmd.none )
                                    else
                                        mergeConsumers <|
                                            Utils.AutoSuggestInput.selectMsg model name subMsg

                                _ ->
                                    mergeConsumers <|
                                        Utils.AutoSuggestInput.selectMsg model name subMsg

                        _ ->
                            mergeConsumers <|
                                Utils.AutoSuggestInput.selectMsg model name subMsg
```

**Comment by MarkNijhof** [comment]
For context, I am using the Select component to search in a list containing all sea ports, which is fairly large. Not searching until there are 3 chars typed would improve the UX

**Comment by sporto** [comment]
I think this needs to be a configuration option. Couple of alternatives I can think of:

- An option like `withMinimumQuerySize Int` where you can set 3
- Or an option to pass a function takes the query and returns True or False to trigger the search or not

I prefer not to expose the messages.

**Comment by MarkNijhof** [comment]
I understand, I like the later one as that gives more flexibility

**Comment by sporto** [comment]
Here is a PR for this https://github.com/sporto/elm-select/pull/9

But question for you. What do you expect to happen when the query is less than 3 chars? 
a) Show all items or 
b) Show no items at all.

At the moment when I type an empty space the list will show the first 12 items. I think this is useful because it allows discoverability.

**Comment by MarkNijhof** [comment]
I would expect no items actually as the search is not executed yet

**Comment by sporto** [comment]
Published 2.8.0. Have a try.

**Comment by MarkNijhof** [comment]
Hey @sporto thanks for this, perfect!

Sorry for the late feedback though :(

**Comment by rlopzc** [comment]
Hi, I'm using this feature with `withOnQuery` and still searches, event if I'm returning `Nothing` from `withTransformQuery`
